# Generated by Django 5.1.3 on 2025-03-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weatherforecast",
            old_name="precipitation_probability_max",
            new_name="precipitation_probability_mean",
        ),
    ]
